# Save this file as run_planner.py
import subprocess
import sys

def run_main_script(query: str):
    """
    Runs the main2.py script with a given query using a subprocess.
    """
    # The command to execute, with each part as an element in a list.
    # This is a secure way to pass arguments without shell injection.
    command = [sys.executable, "main2.py", query]
    
    print(f"--- Running planner for query: '{query}' ---")
    
    try:
        # We use a context manager to run the process
        # stdout=subprocess.PIPE lets us see the live output
        # text=True decodes the output as text
        with subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1) as proc:
            # Print each line of output as it's generated by main2.py
            if proc.stdout:
                for line in proc.stdout:
                    print(line, end='')

        if proc.returncode != 0:
            print(f"\n--- Script finished with an error (exit code {proc.returncode}) ---")
        else:
            print("\n--- Script finished successfully ---")
            
    except FileNotFoundError:
        print(f"Error: Could not find 'main2.py'. Make sure this script is in the same directory.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    # Define the travel query you want to run
    travel_query = "Plan a trip from Mumbai to Paris from 10th October for 21 days"
    
    # Call the function to run the main script
    run_main_script(travel_query)